### ISSUE TITLE
Custom themes, templates

### ISSUE THREAD

**Issue by 3vivekb** [keitaroinc/docker-ckan#1]
Any ideas on a smart way to handle the Frontend - custom themes, templates, to both allow for production releases as well as development?

**Comment by mbocevski** [comment]
Yes you would have your ckan extensions and install them within a docker image derrived from this one.  If you pass on tags or mount the extensions to that docker image then you can use that for development. For production you just tag the image to make a release and deploy.

Your Dockerfile will look like for instance:
`FROM keitaro/ckan:2.5.3

RUN pip install -e git+https://github.com/keitaroinc/ckanext-s3filestore.git#egg=ckanext-s3filestore && \
         pip install -e git+https://github.com/3vivekb/ckanext-mycustomckantheme.git#egg=ckanext-mycustomckantheme

# Add the new plugins you just installed before
ENV CKAN__PLUGINS image_view text_view recline_view datastore datapusher envvars s3filestore mycustomckantheme

# Load envvars plugin in ini file
RUN paster --plugin=ckan config-tool /etc/ckan/default/production.ini "ckan.plugins = ${CKAN__PLUGINS}"`

**Comment by mbocevski** [comment]
@3vivekb did you manage to use the instructions above? I think that we need to add a readme here to make things easier. Can you please confirm?

**Comment by 3vivekb** [comment]
Hey @mbocevski I haven't tested this yet - moved to another project.  I'll try it out this afternoon.

**Comment by Ik-Emmanuel** [comment]
@3vivekb did you figure out how to do this. I have been looking for a way to get a production keitaro ckan image to install and register a custom extenion during build , for the sole-purpose of editing and overwirting template and public files. customizing the look and style of my CKAN site. Please help

**Comment by 3vivekb** [comment]
Sorry @Ik-Emmanuel I don't think I ever solved this.  We closed down our project a long time ago for an ESRI solution, which honestly, was more maintainable for us.
