### ISSUE TITLE
[FEATURE] Update CKAN to 2.9.9

### ISSUE THREAD

**Issue by b-a0** [keitaroinc/docker-ckan#101]
**Is your feature request related to a problem? Please describe.**
CKAN < 2.9.9 has a [critical vulnerability](https://github.com/ckan/ckan/security/advisories/GHSA-446m-hmmm-hm8m) that is patched in 2.9.9. 

**Describe the solution you'd like**
Provide an image for CKAN version 2.9.9/

**Describe alternatives you've considered**
I've considered using my own Dockerimage or using the [official CKAN image](https://github.com/ckan/ckan-docker-base).

**Additional context**
N/A

**Comment by Filip3mac** [comment]
@blazhovsky We need to take a look at this.

**Comment by Filip3mac** [comment]
Merged https://github.com/keitaroinc/docker-ckan/pull/102
