### ISSUE TITLE
[BUG] Why is the JWT encode/decode token replaced by the start script?

### ISSUE THREAD

**Issue by b-a0** [keitaroinc/docker-ckan#107]
[`start_ckan.sh`](https://github.com/keitaroinc/docker-ckan/blob/master/images/ckan/2.9/setup/app/start_ckan.sh) replaces the `api_token.jwt.encode.secret` and `api_token.jwt.decode.secret` values when the `beaker.session.secret` is empty (which it is by default).

I understand that one can set these values in the `.ckan-env` file, but I don't understand why that is needed? If you let `ckan` just create its config (`ckan generate config`) these keys get a default value. Why not keep that default value and only overwrite through env vars when it is not sufficient?

**Comment by blazhovsky** [comment]
@b-a0 this is a known security issue. You can see the changes [here](https://github.com/keitaroinc/docker-ckan/pull/86)
