### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huriviades** [keitaroinc/docker-ckan#111]
**Describe the bug**
The datapusher throws an error that the requests and tzdata packages are not installed, when it installed with the pip. Later, I upload a csv file to generate the datapusher and it fails with an error:  Error getting due jobs from job store 'default': columns argument to select() must be a Python list or other iterable. 

**Docker images affected**
CKAN 2.8 - Alpine Linux
Datapusher - Alpine Linux, ghcr.io/keitaroinc/datapusher:0.0.17

**Expected behaviour**
 Error getting due jobs from job store 'default': columns argument to select() must be a Python list or other iterable

**Comment by hbenkhay** [comment]
yeah I am having the same issues as well, the other bug is because of a version change in Sqlalchemy, I managed to fix it using `SQLAlchemy==1.3.19`

**Comment by stojanovskis1** [comment]
Duplicate of #114
