### ISSUE TITLE
Add nginx/letsencrypt container

### ISSUE THREAD

**Issue by dpadron** [keitaroinc/docker-ckan#55]
Hi good morning.
Could someone guide me on how to configure NGINX-Proxy-manager with keitaroinc / docker-ckan
Or if someone has managed to integrate a service in the docker-compose.yml with nginx and letsencrypt
I appreciate the help

**Comment by mbocevski** [comment]
Don't know about nginx proxy manager, although it looks like a simple app to setup. But you can probably configure traefik with acme (letsencrypt).

**Comment by dpadron** [comment]
Thanks, use Nginx Proxy manager and it works fine.
I leave the link in case it was of interest:
https://github.com/jc21/nginx-proxy-manager
