### ISSUE TITLE
[BUG] Error message with default install...

### ISSUE THREAD

**Issue by infracritical** [keitaroinc/docker-ckan#64]
Trying out the default/standard installation as provided for a docker-compose build/install.

I receive the following error message towards the end of log:

db            | PostgreSQL init process complete; ready for start up.
db            | 
db            | 2022-01-21 01:42:48.578 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db            | 2022-01-21 01:42:48.578 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db            | 2022-01-21 01:42:48.605 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db            | 2022-01-21 01:42:48.641 UTC [105] LOG:  database system was shut down at 2022-01-21 01:42:48 UTC
db            | 2022-01-21 01:42:48.653 UTC [1] LOG:  database system is ready to accept connections
solr          | 2022-01-21 01:42:51.949 INFO  (qtp314337396-13) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*&wt=json} hits=0 status=0 QTime=45
**ckan          | [prerun] Start check_db_connection...
ckan          | could not connect to server: Connection refused
ckan          | 	Is the server running on host "db" (172.19.0.4) and accepting
ckan          | 	TCP/IP connections on port 5432?
ckan          | 
ckan          | [prerun] Unable to connect to the database...try again in a while.
ckan          | [prerun] Start check_db_connection...
ckan          | could not connect to server: Connection refused
ckan          | 	Is the server running on host "db" (172.19.0.4) and accepting
ckan          | 	TCP/IP connections on port 5432?
ckan          | 
ckan          | [prerun] Unable to connect to the database...try again in a while.
ckan          | [prerun] Start check_db_connection...
ckan          | [prerun] Start check_solr_connection...
ckan          | Traceback (most recent call last):
ckan          |   File "prerun.py", line 213, in <module>
ckan          |     check_solr_connection()
ckan          |   File "prerun.py", line 86, in check_solr_connection
ckan          |     conn_info = re.sub(r'"zkConnected":false', '"zkConnected":False', conn_info.decode('utf-8'))
ckan          | AttributeError: 'str' object has no attribute 'decode'
ckan          | [CKAN prerun] FAILED. Exiting...
ckan exited with code 1**

**Comment by blazhovsky** [comment]
@infracritical this was fixed the next day, sorry that I didn't inform you.

After merging #68 we also added support for SOLR 8 since CKAN 2.9.5 supports it.
