### ISSUE TITLE
Support Solr 8

### ISSUE THREAD

**Issue by rjruizes** [keitaroinc/docker-ckan#67]
CKAN 2.9.5 supports Solr 8. This repo only supports Solr 6.6.6 ([Dockerfile](https://github.com/keitaroinc/docker-ckan/blob/master/compose/solr/Dockerfile))

**Comment by blazhovsky** [comment]
@rjruizes SOLR 8 is now supported after merging #68. We didn't run into issues during our tests so I'm closing this issue.

**Comment by rjruizes** [comment]
Thanks. Looks like your solution is equivalent to the [`ckan/ckan-solr:2.9-solr8`](https://github.com/ckan/ckan-solr) image, which I'll probably use since it doesn't require mounting a volume at runtime.

**Comment by mbocevski** [comment]
@rjruizes it's better not to use a custom image for SOLR, cause the way that we've implemented will make it easy to update SOLR versions by simply just changing the SOLR image tag. Also as we do it in helm, this is better for kubernetes based deployments as well.
