### ISSUE TITLE
[BUG] Docker image doesn't work : uwsgi

### ISSUE THREAD

**Issue by vvvlll93** [keitaroinc/docker-ckan#75]
**Describe the bug**
Since the last upgrade [(this commit)](https://github.com/keitaroinc/docker-ckan/commit/ff81bdb5d56927205ad053b8681e26fc70a2c3f9), the docker image doesn't work anymore. When launching the image, we don't go pass the uwsgi step.

**Docker images affected**
CKAN 2.9

**Expected behaviour**
We would expect it to work, the problem seems to come from the upgraded version of uwsgi

**Logs**
ckan        | [prerun] Start check_db_connection...
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Succesfully connected to solr and CKAN schema loaded
ckan        | [prerun] Start init_db...
ckan        | [prerun] Initializing or upgrading db - start using ckan db init
ckan        | [prerun] Initializing or upgrading db - end
ckan        | [prerun] Initializing or upgrading db - finish
ckan        | [prerun] Initializing datastore db - start
ckan        | [prerun] Initializing datastore db - end
ckan        | b''
ckan        | [prerun] Start create_sysadmin...
ckan        | [prerun] Sysadmin user exists, skipping creation
ckan        | *** Starting uWSGI 2.0.19.1 (64bit) on [Tue Jul 12 09:00:19 2022] ***
ckan        | compiled with version: 10.2.1 20201203 on 20 January 2022 14:43:45
ckan        | os: Linux-5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
ckan        | nodename: b6f0c77c3118
ckan        | machine: x86_64
ckan        | clock source: unix
ckan        | pcre jit disabled
ckan        | detected number of CPU cores: 8
ckan        | current working directory: /srv/app
ckan        | detected binary path: /usr/bin/uwsgi
ckan        | your memory page size is 4096 bytes
ckan        |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
ckan        | detected max file descriptor number: 1048576
ckan        | - async cores set to 2000 - fd table size: 1048576
ckan        | lock engine: pthread robust mutexes
ckan        | thunder lock: disabled (you can enable it with --thunder-lock)
ckan        | uWSGI http bound on :5000 fd 3
ckan        | uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 6
ckan        | Python version: 3.8.10 (default, May  6 2021, 00:05:59)  [GCC 10.2.1 20201203]
ckan        | Python main interpreter initialized at 0x7f225afcb990
ckan        | python threads support enabled
ckan        | your server socket listen backlog is limited to 100 connections
ckan        | your mercy for graceful operations on workers is 60 seconds
ckan        | mapped 62923392 bytes (61448 KB) for 4000 cores
ckan        | *** Operational MODE: preforking+async ***
ckan        | *** uWSGI is running in multiple interpreter mode ***
ckan        | spawned uWSGI master process (pid: 14)
ckan        | spawned uWSGI worker 1 (pid: 16, cores: 2000)
ckan        | spawned uWSGI worker 2 (pid: 17, cores: 2000)
ckan        | spawned uWSGI http 1 (pid: 18)

**Comment by vvvlll93** [comment]
Hi ! I'm using the ubuntu image !

**Comment by abdou-ghonim** [comment]
The same here also happens with the alpine image too. no errors in the ckan container logs but docker is reporting that the CKAN container is "unhealthy" and the CKAN website on http://localhost:5000 is not working.

**Comment by vvvlll93** [comment]
I observed the same problem on the ubuntu image as @abdou-ghonim

**Comment by abdou-ghonim** [comment]
It is working now. thanks @blazhovsky

**Comment by blazhovsky** [comment]
Glad to hear that @abdou-ghonim. Closing this issue.

**Comment by Suryakandukuri** [comment]
Hi I was trying to run docker-compose up --build, a few min ago. Ran into this error.

ckan        | *** Starting uWSGI 2.0.20 (64bit) on [Fri Jul 15 06:13:33 2022] ***
ckan        | compiled with version: 10.2.1 20201203 on 07 July 2022 15:20:50
ckan        | os: Linux-5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022
ckan        | nodename: cef920dee5a8
ckan        | machine: x86_64
ckan        | clock source: unix
ckan        | pcre jit disabled
ckan        | detected number of CPU cores: 5
ckan        | current working directory: /srv/app
ckan        | detected binary path: /usr/bin/uwsgi
ckan        | your memory page size is 4096 bytes
ckan        |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
ckan        | detected max file descriptor number: 1048576
ckan        | - async cores set to 2000 - fd table size: 1048576
ckan        | lock engine: pthread robust mutexes
ckan        | unable to set PTHREAD_PRIO_INHERIT
ckan exited with code 1

Please help with this. Thanks

**Comment by rady-msaad** [comment]
@Suryakandukuri : did you find any solution

**Comment by blazhovsky** [comment]
@rady-msaad are you still having issues like this? We have new images pushed and we haven't run into any issue like this, but maybe try to get the latest version and see what happens.

**Comment by rady-msaad** [comment]
Hi @blazhovsky yes. 
I believe its platform specific. Its working on mac but throws error on windows 10 (WSL2 linux container)
And it's not specific to ckan. 
 
<img width="990" alt="image" src="https://user-images.githubusercontent.com/90284347/219087569-81589b3c-f1e5-4d58-a20a-b34a9eb05a71.png">

**Comment by CarlosAlbertoUFS** [comment]
I'm working with mac arm m1 and the same problem happens.
