### ISSUE TITLE
[BUG] Unable to connect to Solr

### ISSUE THREAD

**Issue by tpgmartin** [keitaroinc/docker-ckan#77]
**Describe the bug**
Have tried to clone, build, and run the project following the instructions in the readme, however ckan container exits shortly after running. I'm trying the run this on an Azure VM running Linux (ubuntu 18.04).

**Docker images affected**
CKAN 2.9 (I've only tried this version)

**Expected behaviour**
Containers to run successfully on default ports

**Logs**
```
ckan        | [prerun] Start check_db_connection...
ckan        | could not connect to server: Connection refused
ckan        | 	Is the server running on host "db" (172.20.0.3) and accepting
ckan        | 	TCP/IP connections on port 5432?
ckan        |
ckan        | [prerun] Unable to connect to the database...try again in a while.
ckan        | [prerun] Start check_db_connection...
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Unable to connect to solr...try again in a while.
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Unable to connect to solr...try again in a while.
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Unable to connect to solr...try again in a while.
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Unable to connect to solr...try again in a while.
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Unable to connect to solr...try again in a while.
ckan        | [prerun] Start check_solr_connection...
ckan        | [prerun] Giving up after 5 tries...
ckan        | [CKAN prerun] FAILED. Exiting...
```

**Comment by lknite** [comment]
I'm not part of the support team here, but just looking at the logs it doesn't look like there is a database running.  Is there a database running anywhere?

**Comment by blazhovsky** [comment]
@tpgmartin how did you run the image? Did you use the docker-compose setup or just the image? Because it looks like you just ran the CKAN image.

@lknite although we are responsible for maintaining our repos, feel free to help anyone that asks for help or open up PRs with fixes that you have. This is an open source project after all and we would love to expand the CKAN community.

**Comment by Filip3mac** [comment]
Stale issue
