### ISSUE TITLE
[BUG] Customizing container instructions, url no longer exists: github.com/acmecorp/ckanext-acme

### ISSUE THREAD

**Issue by lknite** [keitaroinc/docker-ckan#78]
**Describe the bug**
In the instructions for building a customized image a url used no longer exists:
https://github.com/acmecorp/ckanext-acme

**Expected behaviour**
Copy example Dockerfile and 'docker build .' successfully

**Additional**
Is there an updated url, or do we really need that line in the Dockerfile?

**Comment by blazhovsky** [comment]
That is a completely made up extension just to show a user how a potential custom extension would look and be used.
