### ISSUE TITLE
[BUG] 502 related to uwsgi header size

### ISSUE THREAD

**Issue by lknite** [keitaroinc/docker-ckan#79]
**Describe the bug**
Some of my coworkers immediately see a 502 when accessing ckan, while others get the ckan site no problem.  If they open up an incognito browser they see the ckan site without issue.

Logs show errors when my coworkers are getting the 502.  It looks related to the uwsgi header size.

I found a posting where people discuss different ways to solve this:
https://stackoverflow.com/questions/15878176/uwsgi-invalid-request-block-size

Which suggests the buffer size configured with uwsgi is configured small by default (4096) and should be increased.
Alternatively, other solutions suggest the 'protocol' might need to be adjusted in the uwsgi settings.

**Expected behaviour**
Everyone able to access the ckan site consistently

**Logs**
```
invalid request block size: 4313 (max 4096)...skip
[uwsgi-http key: ckan.its-cdo-non.k.idaho.gov client_addr: 192.168.1.3 client_port: 13549] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4313 (max 4096)...skip
[uwsgi-http key: ckan.its-cdo-non.k.idaho.gov client_addr: 192.168.1.3 client_port: 14061] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
```

**Comment by blazhovsky** [comment]
Thanks for reporting this @lknite, I also saw your [other ticket](https://github.com/keitaroinc/ckan-helm/issues/41) on the helm chart repo. We'll look into this
