### ISSUE TITLE
ckan | [prerun] Unable to connect to solr...try again in a while

### ISSUE THREAD

**Issue by technoashn** [keitaroinc/docker-ckan#84]
I have ran the containers per the instructions provided and using compose setup but getting the below issue.

ckan          | [prerun] Start check_db_connection...
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Unable to connect to solr...try again in a while.
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Unable to connect to solr...try again in a while.
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Unable to connect to solr...try again in a while.
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Unable to connect to solr...try again in a while.
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Unable to connect to solr...try again in a while.
ckan          | [prerun] Start check_solr_connection...
ckan          | [prerun] Giving up after 5 tries...
ckan          | [CKAN prerun] FAILED. Exiting...
ckan exited with code 1

However I checked all the containers status, seems all are in running state

CONTAINER ID   IMAGE                                  COMMAND                  CREATED             STATUS                    PORTS                                       NAMES
3a4b27a77fc9   ghcr.io/keitaroinc/datapusher:0.0.17   "uwsgi --socket=/tmp…"   About an hour ago   Up 16 minutes             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   datapusher
dd56dc759632   redis:6.0.7                            "docker-entrypoint.s…"   About an hour ago   Up 16 minutes             6379/tcp                                    redis
0010805baec9   solr:8.11.1                            "docker-entrypoint.s…"   About an hour ago   Up 16 minutes             8983/tcp                                    solr
ba850fb207c1   29_db                                  "docker-entrypoint.s…"   About an hour ago   Up 16 minutes (healthy)   5432/tcp                                    db

Please help. Thank you.

**Comment by Aadesh-Baral** [comment]
I'm also facing similar issue.

**Comment by Filip3mac** [comment]
This issues is fixed with the following pr https://github.com/keitaroinc/docker-ckan/commit/cd2af213676f7358ed96485bbf929e5cedc5aa4b
