### ISSUE TITLE
[FEATURE] Update github actions

### ISSUE THREAD

**Issue by blazhovsky** [keitaroinc/docker-ckan#88]
**Is your feature request related to a problem? Please describe.**
Currently the github actions are showing a warning (e.g. https://github.com/keitaroinc/docker-ckan/actions/runs/4043947051) about a deprecated command

**Describe the solution you'd like**
We need to update the github actions accordingly.

**Comment by stojanovskis1** [comment]
Closing issue, github actions updated #126 PR.
