### ISSUE TITLE
[FEATURE] failed starting up

### ISSUE THREAD

**Issue by pvgenuchten** [keitaroinc/docker-ckan#89]
**Is your feature request related to a problem? Please describe.**
Hi there, i like very much your detailed description on how to extend ckan with extensions using docker. However I have quite problems starting up the system, when i run a docker compose build && up, i get following errors, maybe related:

- 2.8:
   - ckan        |   File "/srv/app/src/ckan/ckan/lib/config_tool.py", line 35, in config_edit
     ckan        |     with open(config_filepath, 'rb') as f:
     ckan        | IOError: [Errno 21] Is a directory: '/srv/app' 
     db          | /usr/local/bin/docker-entrypoint.sh: line 170: /docker-entrypoint-initdb.d/00_create_datastore.sh: cannot execute: required file not found
- 2.9: 
   - ckan        |   File "/srv/app/src/ckan/ckan/lib/config_tool.py", line 37, in config_edit
     ckan        |     with open(config_filepath, 'rb') as f:
     ckan        | IsADirectoryError: [Errno 21] Is a directory: '/srv/app'
   - ckan        | [prerun] Unable to connect to solr...try again in a while.
     ckan        | [prerun] Start check_solr_connection...
     ckan        | [prerun] Giving up after 5 tries...

I have not taken time to check what's going on

update: 
- with version 2.9.6 the error does not occur
- for me a volume with ${PWD} did not work, used `- ./solr8/ckan_init_solr.sh:/docker-entrypoint-initdb.d/ckan_init_solr.sh` instead

**Comment by bicisteadm** [comment]
Hello,
my pull request #90 fixes this bug.

**Comment by blazhovsky** [comment]
We merged #90 so I'm closing this as resolved.
