### ISSUE TITLE
ckanext-envvars must be the last plugin entry

### ISSUE THREAD

**Issue by MarijaKnezevic** [keitaroinc/docker-ckan#92]
Hey
accordingly to the https://github.com/okfn/ckanext-envvars#requirements the ckanext-envvars should be the last plugin entry in the pluginlist.

**Comment by Filip3mac** [comment]
Hey @MarijaKnezevic did you have any problems with this extension? If so please explain so we can help you.

**Comment by Filip3mac** [comment]
Closing this issue as no response from @MarijaKnezevic
