### ISSUE TITLE
[BUG] Datapusher not uploading files 

### ISSUE THREAD

**Issue by OGrigorios** [keitaroinc/docker-ckan#99]
**Describe the bug**
When uploading data in csv format to the FileStore that upload to DataStore doesn't work.
The logs from the datapusher container is:

**Docker images affected**
1. CKAN 2.9

**Expected behaviour**
The file will be added to the datastore

**Logs**
```datapusher  | Error getting due jobs from job store 'default': columns argument to select() must be a Python list or other iterable```

**Comment by blagojabozinovski** [comment]
Looks like the the problem is that value that You want iterate through is None. This can be because there is no connection to the datapusher or problem with the SQLAlchemy version. Can You provide the full log so we have more info?

**Comment by blagojabozinovski** [comment]
Will reopen ticket on feedback.
